output_dir: ~/MOTIF/output

dataset:
  class: {{ dataset }}
  root: ~/MOTIF/kg-datasets/

model:
  class: MOTIF
  relation_model:
    class: HCNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    short_cut: yes
    use_triton: yes
    aggregate_func: sum
  entity_model:
    class: IndNBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    use_triton: yes

task:
  name: TransductiveInference
  num_negative: 256
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]


train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: {{ epochs }}
  log_interval: 100
  batch_per_epoch: {{ bpe }}

checkpoint: {{ ckpt }}